layout: stack
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: push
  sort_by options:
     - pushed
     - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
   linkedin: akshahi17
  # behance: your_username
  # dribbble: your_username
   facebook: akshahi17
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
   stackoverflow: 10263598
  # telegram: your_username
   twitter: akshahi_17
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
 
   
topics:
  - name: Python
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Matlab
    web_url: https://in.mathworks.com/products/matlab.html
    image_url: https://user-images.githubusercontent.com/42636201/92883089-2da9d800-f42e-11ea-89ac-a56552cfcfa4.gif
    
  - name: R
    web_url: https://github.com/topics/r
    image_url: https://user-images.githubusercontent.com/42636201/92883854-e53eea00-f42e-11ea-8c24-b3c7d6cb8543.jpg

theme: jekyll-theme-cayman

